artifacts_root: artifacts

# data ingestion is all about downloading the data from source, here the source is github
# local_data_file is the location of the downloaded data
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rohitspatil30/diabetes_classification_project/raw/master/datasets/diabetes_dataset.zip
  local_data_file: artifacts/data_ingestion/diabetes_dataset.zip
  unzip_dir: artifacts/data_ingestion

# data validation is all about validating the data
# local_data_file is the location of the downloaded data


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/diabetes.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/diabetes.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
